version: '3'
services:
  db:
    image: "apache/couchdb:2.1.1"
  app:
    build: .
    environment:
      - COUCHDB_URL=http://db:5984
    links:
      - "db"
    depends_on:
      - "db"
  dbconfig:
    build: .
    entrypoint: "scripts/dbSetup.sh"
    environment:
      - COUCHDB_URL=http://db:5984
    links:
      - "db"
    depends_on:
      - "db"
